import Men1 from "../assets/Product Images/Mens/1.jpg"
import Men2 from "../assets/Product Images/Mens/2.jpg"
import Men3 from "../assets/Product Images/Mens/3.jpg"
import Men4 from "../assets/Product Images/Mens/4.jpg"
import Men5 from "../assets/Product Images/Mens/5.jpg"
import Men6 from "../assets/Product Images/Mens/6.jpg"
import Men7 from "../assets/Product Images/Mens/7.jpg"
import Men8 from "../assets/Product Images/Mens/8.jpg"
import Woman1 from "../assets/Product Images/Womans/1.jpg"
import Woman2 from "../assets/Product Images/Womans/2.jpg"
import Woman3 from "../assets/Product Images/Womans/3.jpg"
import Woman4 from "../assets/Product Images/Womans/4.jpg"
import Woman5 from "../assets/Product Images/Womans/5.jpg"
import Woman6 from "../assets/Product Images/Womans/6.jpg"
import Woman7 from "../assets/Product Images/Womans/7.jpg"
import Woman8 from "../assets/Product Images/Womans/8.jpg"

const productData = [
  {
    id: 1,
    image: Men1,
    title: "Men's Short Sleeve Printed Shirt",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 1295,
    description:
      "Turn heads with this shirt, featuring an intricate geometric print.Crafted from soft, breathable fabric, it combines comfort with bold style. The tailored fit and classic collar make it versatile — perfect for weekend outings, or smart summer looks.",
    color: "#222357",
    colorName: "Navy Blue",
    sizes: ["S", "M", "L", "XL"],
    brand: "Moose",
    defaultSize: "M",
    sku: "KS2986",
    category: "men-new",
  },
  {
    id: 2,
    image: Men2,
    title: "Lacoste Athlete Crew Neck T Shirt",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 1095,
    description:
      "Made from 100% organic cotton. Minimalist in design and ultra-comfortable, it’s your go-to for everyday wear.",
    color: "#4E7F62",
    colorName: "Ash Green",
    sizes: ["S", "M", "L"],
    brand: "Moose",
    defaultSize: "M",
    sku: "KA5892",
    category: "men-new",
  },
  {
    id: 3,
    image: Men3,
    title: "Men's Slim Fit Mid Washed Jean",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 4495,
    description:
      "These jeans offer a modern slim fit with just the right amount of stretch. Perfect for any casual or semi-formal outfit.",
    color: "#222357",
    colorName: "Dark Blue",
    sizes: ["30", "32", "34", "36"],
    brand: "Moose",
    defaultSize: "32",
    sku: "PW3147",
    category: "men-new",
  },
  {
    id: 4,
    image: Men4,
    title: "Moose Men's Chino Pant ",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 3495,
    description:
      "Elegantly tailored white shirt in breathable cotton. Ideal for office or formal occasions.",
    color: "#000000",
    colorName: "Black",
    sizes: ["S", "M", "L", "XL"],
    brand: "Moose",
    defaultSize: "L",
    sku: "LS5523",
    category: "men-new",
  },
  {
    id: 5,
    image: Men5,
    title: "Long Sleeve Fit Tie-Neck Top",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 3200,
    description:
      "Stay warm and stylish with this fleece-lined hoodie. Features a modern fit and adjustable drawstring hood.",
    color: "#222357",
    colorName: "Navy Blue",
    sizes: ["S", "M", "L", "XL", "XXL"],
    brand: "Moose",
    defaultSize: "L",
    sku: "MM2587",
    category: "men-new",
  },
  {
    id: 6,
    image: Men6,
    title: "Hustle Mens Lucid T-Shirt",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 1195,
    description:
      "Rugged and reliable, these cargo pants feature side pockets and durable stitching for everyday adventure.",
    color: "#BAF2A2",
    colorName: "Light Green",
    sizes: ["30", "32", "34", "36"],
    brand: "Moose",
    defaultSize: "34",
    sku: "BN3642",
    category: "men-new",
  },
  {
    id: 7,
    image: Men7,
    title: "Moose Double Pocket Textured 2 pcs Set",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 5395,
    description:
      "Timeless design with a modern edge. This denim jacket is a must-have for layering in any season.",
    color: "#89817B",
    colorName: "Hurricane",
    sizes: ["S", "M", "L", "XL"],
    brand: "Moose",
    defaultSize: "M",
    sku: "CV2233",
    category: "men-new",
  },
  {
    id: 8,
    image: Men8,
    title: "Long Sleeve Fit Tie-Neck Top",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 4395,
    description:
      "Soft, breathable cotton tee with bold stripes. Casual yet trendy — pair it with shorts or jeans.",
    color: "#975A03",
    colorName: "Brown",
    sizes: ["S", "M", "L"],
    defaultSize: "M",
    brand: "Moose",
    sku: "ZX6654",
    category: "men-new",
  },
  {
    id: 9,
    image: Woman1,
    title: "Men's Short Sleeve Printed Shirt",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 1295,
    description: 
      " " ,
    color: "#222357",
    colorName: "Navy Blue",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "DS5511",
    category: "women-new",
  },
  {
    id: 10,
    image: Woman2,
    title: "Lacoste Athlete Crew Neck T Shirt",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 1095,
    description: 
      " " ,
    color: "#4E7F62",
    colorName: "Ash Green",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "ML4531",
    category: "women-new",
  },
  {
    id: 11,
    image: Woman3,
    title: "Men's Slim Fit Mid Washed Jean",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 4495,
    description: 
      " " ,
    color: "#222357",
    colorName: "Dark Blue",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "DS5563",
    category: "women-new",
  },
  {
    id: 12,
    image: Woman4,
    title: "Moose Men's Chino Pant ",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 3495,
    description: 
      " " ,
    color: "#000000",
    colorName: "Black",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "WQ8743",
    category: "women-new",
  },
  {
    id: 13,
    image: Woman5,
    title: "Long Sleeve Fit Tie-Neck Top",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 3200,
    description: 
      " " ,
    color: "#222357",
    colorName: "Navy Blue",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "AB3612",
    category: "women-new",
  },
  {
    id: 14,
    image: Woman6,
    title: "Hustle Mens Lucid T-Shirt",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 2195,
    description: 
      " " ,
    color: "#BAF2A2",
    colorName: "Light Green",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "SP3378",
    category: "women-new",
  },
  {
    id: 15,
    image: Woman7,
    title: "Moose Double Pocket Textured 2 pcs Set",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 5395,
    description: 
      " " ,
    color: "#89817B",
    colorName: "Hurricane",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "GG8899",
    category: "women-new",
  },
  {
    id: 16,
    image: Woman8,
    title: "Long Sleeve Fit Tie-Neck Top",
    stockStatus: ["In Stock","Out of Stock"],
    defaultStockStatus: "In Stock",
    price: 4395,
    description: 
      " " ,
    color: "#975A03",
    colorName: "Brown",
    sizes: ["S", "M", "L", "XL"],
    defaultSize: "M",
    sku: "AH4512",
    category: "women-new",
  },
];

export default productData;
